# Generated by Django 5.0.3 on 2024-03-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
