version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PG_DATA: /var/vib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/vib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:


