version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PG_DATA: /var/vib/postgresql/data/pgdata

  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db



