# Generated by Django 5.0.3 on 2024-03-06 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='place of action')),
                ('action_datetime', models.DateTimeField(verbose_name='data and time of action')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('nice_feeling', models.BooleanField(default=False, verbose_name='a sign of a pleasant feeling')),
                ('frequency', models.CharField(choices=[('week', 'once a week'), ('every_day', 'every day')], default='every_day', verbose_name='Periodicity')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='reward')),
                ('time_to_complete', models.DurationField(verbose_name='time to complete')),
                ('is_public', models.BooleanField(default=True, verbose_name='sign of publicity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useful_habits.habit', verbose_name='related habit')),
            ],
            options={
                'verbose_name': 'feeling',
                'verbose_name_plural': 'feelings',
            },
        ),
    ]
