# Generated by Django 5.0.3 on 2024-03-07 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='action_datetime',
        ),
        migrations.AddField(
            model_name='feeling',
            name='action_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 7, 4, 19, 46, 998316, tzinfo=datetime.timezone.utc), verbose_name='time of action'),
        ),
    ]
