# Generated by Django 5.0.3 on 2024-03-07 05:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0002_remove_feeling_action_datetime_feeling_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='action_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 7, 5, 12, 51, 40993, tzinfo=datetime.timezone.utc), verbose_name='time of action'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='time_to_complete',
            field=models.DurationField(validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='time to complete'),
        ),
    ]
