# Generated by Django 5.0.3 on 2024-03-07 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0003_alter_feeling_action_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='nice_feeling',
        ),
        migrations.AddField(
            model_name='habit',
            name='nice_feeling',
            field=models.BooleanField(default=False, verbose_name='a sign of a pleasant feeling'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='action_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 7, 5, 50, 23, 790695, tzinfo=datetime.timezone.utc), verbose_name='time of action'),
        ),
    ]
