# Generated by Django 5.0.3 on 2024-03-08 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0004_remove_feeling_nice_feeling_habit_nice_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True, verbose_name='last due date'),
        ),
        migrations.AddField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=7, verbose_name='frequency of habit execution'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='action_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 8, 4, 14, 4, 437398, tzinfo=datetime.timezone.utc), verbose_name='time of action'),
        ),
    ]
