# Generated by Django 5.0.3 on 2024-03-10 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0007_remove_feeling_is_public_habit_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='action_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time of action'),
        ),
    ]
