# Generated by Django 5.0.3 on 2024-03-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0008_alter_feeling_action_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeling',
            name='action_time',
        ),
    ]
