# Generated by Django 5.0.3 on 2024-03-23 13:21

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_habits', '0009_remove_feeling_action_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='nice_feeling',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('week', 'once a week'), ('every_day', 'every day')], default='every_day', verbose_name='Periodicity'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Is a pleasant habit?'),
        ),
        migrations.AddField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_habits', to='useful_habits.habit', verbose_name='Linked Habit'),
        ),
        migrations.AddField(
            model_name='habit',
            name='perform_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Time to perform the habit'),
        ),
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of action'),
        ),
        migrations.AddField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reward'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_to_complete',
            field=models.DurationField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=120))], verbose_name='time to complete'),
        ),
        migrations.DeleteModel(
            name='Feeling',
        ),
    ]
